### HISTORICOS


@baseUrl = http://localhost:3000/api/v1
@contentType = application/json


## GET HISTORICO DE RESGATES



GET {{baseUrl}}/historico/resgates/49137400835
Content-Type: {{contentType}}



